### ISSUE TITLE
run labeler on this repo

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dls-github-labeler#25]

**Comment by inieinie** [comment]
lpass-cli is not working for Eliot or myself

**Comment by hackartisan** [comment]
lastpass-cli had a cert rotation a couple of weeks ago. uninstalling and reinstalling should fix issues.

**Comment by inieinie** [comment]
When I ran this in terminal: lpass show hubot_github_token --notes, it gave me an error that it could not find specified accounts. However, on the lastpass application itself it seems I have access?

**Comment by inieinie** [comment]
Nevermind, figured out that it was a "hide passwords" setting causing issues

**Comment by inieinie** [comment]
Done!
